"""Closed sets of strings used in evidence files (schema 0.1-proto, unstable)."""

# outcome
SYMPTOM_REPRODUCED = "SYMPTOM_REPRODUCED"
SYMPTOM_REPRODUCED_FLAKY = "SYMPTOM_REPRODUCED_FLAKY"
NO_MATCHING_REPRODUCTION_FOUND = "NO_MATCHING_REPRODUCTION_FOUND"
INCONCLUSIVE = "INCONCLUSIVE"
NOT_EVALUATED = "NOT_EVALUATED"

# outcome_reason
NONE = "NONE"
CLAIM_NEEDS_INFO = "CLAIM_NEEDS_INFO"
CLAIM_UNSUPPORTED = "CLAIM_UNSUPPORTED"
CLAIM_PROVENANCE_INSUFFICIENT = "CLAIM_PROVENANCE_INSUFFICIENT"
REPRODUCER_REJECTED = "REPRODUCER_REJECTED"
REPRODUCER_UNSAFE = "REPRODUCER_UNSAFE"
REPRODUCER_NOT_AUDITABLE = "REPRODUCER_NOT_AUDITABLE"
ENVIRONMENT_UNAVAILABLE = "ENVIRONMENT_UNAVAILABLE"
INSUFFICIENT_VALID_RUNS = "INSUFFICIENT_VALID_RUNS"
SINGLE_MATCH_ONLY = "SINGLE_MATCH_ONLY"
TIMEOUT_NOT_CLAIMED = "TIMEOUT_NOT_CLAIMED"
REPOSITORY_MODIFIED = "REPOSITORY_MODIFIED"
VERIFIER_INTERNAL_ERROR = "VERIFIER_INTERNAL_ERROR"

# per-run status
RUN_COMPLETED = "COMPLETED"
RUN_ENV_FAILURE = "ENV_FAILURE"
RUN_TIMEOUT = "TIMEOUT"
RUN_INVALID = "INVALID"

# reproducer gate status
GATE_VALID = "VALID"
GATE_REJECTED = "REJECTED"
GATE_UNSAFE = "UNSAFE"
GATE_NOT_AUDITABLE = "NOT_AUDITABLE"

OBSERVATION_INTEGRITY = "BEST_EFFORT_IN_PROCESS"
